### ISSUE TITLE
Environments Shuffle and Cloud are visible when creating workflows

### ISSUE THREAD

**Issue by m1nk-code** [frikky/shuffle-workflows#4]
When creating a workflow and double clicking on an app, under the environment drop down, options for both Shuffle and Cloud are visible. 

Steps to reproduce (Testing in Chrome browser):

1. Create a new workflow
2. Drag and drop a Test app
3. Double click on it to modify options
4. Select the environment drop down
5. Shuffle and Cloud options are visibile.

![image](https://user-images.githubusercontent.com/58112539/145097999-8fa70314-bf2d-4f84-b1dd-5634d862a544.png)

**Comment by frikky** [comment]
Hey! Do you mind remaking this issue in the main repository? No point in keeping it private.

https://github.com/frikky/Shuffle/issues/new/choose

**Comment by m1nk-code** [comment]
Remade the issue in the main repository and will close this one.
